datawarehouse:
  outputs:
    dev:
      dbname: datawarehouse
      host: localhost
      pass: postgres
      port: 5435
      schema: dbt_dev
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: datawarehouse
      host: localhost
      pass: postgres
      port: 5435
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
